In [1]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv('play_tennis.csv')

In [14]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [15]:
df.drop(columns=['day'], axis=1, inplace=True)

In [16]:
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [17]:
df.isnull().sum()

outlook     0
temp        0
humidity    0
wind        0
play        0
dtype: int64

problem:1

outlook=sunny, temp=hot, humidity=high, wind=weak

play or no play?

solution:
P(yes/sunny, hot, humidity, weak) = p(sunny/yes)*p(hot/yes)*p(humidity/yes)*p(weak/yes)*p(yes)

p(no/sunny, hot, humidity, weak) = p(sunny/no)*p(hot/no)*p(humidity/no)*p(weak/no)*p(no)

In [18]:
#first create lookup table
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [19]:
py = 9/14
pn = 5/14

The above mention technique is not applicalble for large dateset. so we prefer to use another technique.

In [21]:
#outlook
pd.crosstab(df['outlook'], df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [22]:
pon = 0
prn = 2/5
psn = 3/5

poy = 4/9
pry = 3/9
psy = 2/9

In [23]:
#temp
pd.crosstab(df['temp'], df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [24]:
pcoolno = 1/5
photno = 2/5
pmildno = 2/5

pcoolyes = 3/9
photyes = 2/9
pmildyes = 4/9

In [25]:
#humidity
pd.crosstab(df['humidity'], df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [26]:
phighno = 4/5
pnormalno = 1/5

phighyes = 3/9
pnormalyes = 6/9

In [27]:
#wind
pd.crosstab(df['wind'], df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [28]:
pstrongno = 3/5
pweakno = 2/5

pstrongyes = 3/9
pweakyes = 6/9

In [29]:
#outlook = sunny, temp = hot, humidity = high, wind = weak
pyes = py*psy*photyes*phighyes*pweakyes

In [30]:
print(pyes)

0.007054673721340388

In [31]:
pno = pn*psn*photno*phighno*pweakno

In [32]:
print(pno)

0.02742857142857143

Since the probability of play no is greater (0.02) than probability of play tenis yes (0.0070).So, in given condition, playing tenis is prohibited.