PCA is a feature extraction technique. It reduce the dimension of data while keeping the important features.

Benefits of using PCA is:

1. Dimension reduction, memory save, faster execution of algorithm

2. visualization

In [13]:
import numpy as np
import pandas as pd

np.random.seed(23) 

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

df = pd.concat([df, df1],ignore_index=True)

df = df.sample(20)

In [14]:
df.head()

    feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1

In [15]:
import plotly.express as px
#y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
              color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

In [16]:
# Step 1 - Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [17]:
# Step 2 - Find Covariance Matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[ 1.05263158  0.18345809  0.09157879]
 [ 0.18345809  1.05263158 -0.03936926]
 [ 0.09157879 -0.03936926  1.05263158]]

In [18]:
#step 3: finding eigenvalues and eigen vector
eigen_values, eigen_vector = np.linalg.eig(covariance_matrix)

In [19]:
eigen_values

array([0.83006218, 1.24416981, 1.08366274])

In [20]:
eigen_vector

array([[-0.67597553,  0.72707359,  0.12008781],
       [ 0.62597306,  0.65251607, -0.42706031],
       [ 0.3888635 ,  0.21351059,  0.89621337]])

In [22]:
pc = eigen_vector[0:2]
pc

array([[-0.67597553,  0.72707359,  0.12008781],
       [ 0.62597306,  0.65251607, -0.42706031]])

In [23]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# 40,3 - 3,2
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

        PC1       PC2  target
0 -0.743811 -0.383050       1
1 -0.383296 -0.980503       0
2 -0.073047  0.262240       1
3 -1.529062  0.770653       1
4  1.381386 -1.598120       1

In [24]:
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()